blank_issues_enabled: true

contact_links:

  - name: Rapalel

    url: t.me/PalelSupportGRUP

    about: Direct chat on non-inquiries subjects.

  - name: Documentation

    url: t.me/PalelSupportCH

    about: Documentation for getting started with bot.

