blank_issues_enabled: true

contact_links:

  - name: Ditxyz Support

    url: https://t.me/DitxyzSupport

    about: Direct chat on non-inquiries subjects.

  - name: Documentation

    url: https://yukki.tech/

    about: Documentation for getting started with bot.

